Repository davesag/swagger-routes-express, pull requests merged in 2021-01, with the labels that each got.

#177 [optimisation, n/a] upgrade dependencies
  .eslintrc.js
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: dependencies, enhancement

#153 Updated connectController so array can be used as route controllers
  src/connector/connectController.js
  test/unit/connector/connectController.test.js
Labels: documentation, enhancement

#178 [optimisation, n/a] rebuilt package-lock file for npm v7+
  package-lock.json
Labels: dependencies

#179 [documentation, #174] updated documentation regarding arrays of controllers
  README.md
  package.json
  src/connector/connectController.js
Labels: documentation, enhancement
